// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUrJDfWqI1J6f-aTr9zIJrQu2MNvadfWo',
    appId: '1:299508138162:web:7e08a37b3473653a9e09ab',
    messagingSenderId: '299508138162',
    projectId: 'evopdv-app',
    authDomain: 'evopdv-app.firebaseapp.com',
    storageBucket: 'evopdv-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaqQjLMnnUlbOMZV2ideOkqop0JPPkP0Y',
    appId: '1:299508138162:android:3766e544c9e1f0bf9e09ab',
    messagingSenderId: '299508138162',
    projectId: 'evopdv-app',
    storageBucket: 'evopdv-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMbPYAmurJnYp2eYLmhxWH1Vc37s-aNDM',
    appId: '1:299508138162:ios:03bcf738b821b8949e09ab',
    messagingSenderId: '299508138162',
    projectId: 'evopdv-app',
    storageBucket: 'evopdv-app.firebasestorage.app',
    iosBundleId: 'com.example.futuropdv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMbPYAmurJnYp2eYLmhxWH1Vc37s-aNDM',
    appId: '1:299508138162:ios:03bcf738b821b8949e09ab',
    messagingSenderId: '299508138162',
    projectId: 'evopdv-app',
    storageBucket: 'evopdv-app.firebasestorage.app',
    iosBundleId: 'com.example.futuropdv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUrJDfWqI1J6f-aTr9zIJrQu2MNvadfWo',
    appId: '1:299508138162:web:69cbcec9fd7ff4569e09ab',
    messagingSenderId: '299508138162',
    projectId: 'evopdv-app',
    authDomain: 'evopdv-app.firebaseapp.com',
    storageBucket: 'evopdv-app.firebasestorage.app',
  );

}